export {default as About} from './About'
export {default as Course} from './Course'
export {default as BestIntruction} from './BestIntructin'
export {default as CorseMe} from './CorseMe'
export {default as Bener} from './Bener'
export {default as Footer} from './Footer'